language: python

python:
  - "3.8"

services:
  - postgresql

directories:
  - $HOME/.cache/pip

env:
  global:
    - DATABASE_URL=postgres://postgres@localhost:5432/wayne_db
    - SECRET_KEY=thisisasecret
    - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=1085816269462-7lhdascr5pbssj2bb5u2hfr1bf10pak0.apps.googleusercontent.com
    - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=YrgT3gNXxRj_qnBuKPIu4hEI
    - SOCIAL_AUTH_GITHUB_KEY=0afc5297c8e8e21b1737
    - SOCIAL_AUTH_GITHUB_SECRET=ce263d98c06c25c9b0126d41ffc6642a3f3dc6b1

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database wayne_db;' -U postgres

jobs:
  include:
    - stage: 'tests'
      name: 'Tests'
      script:
        - pytest --verbose



before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log


